In [7]:
#Numpy
import numpy as np

grades = np.array([84.33, 91.67, 99.0, 80.0])

print(grades)

#vectorization
bonus = grades + 5
print(bonus)

#Aggregation
print("Mean: ",grades.mean())
print("Maximum: ",grades.max())
print("Minimum: ", grades.min())

#2d array
students_grades = np.array([[85, 90, 78], [92, 88, 95], [100, 99, 98]])
print(students_grades)

print("Average of each student: ", students_grades.mean(axis = 1))

[84.33 91.67 99.   80.  ]
[ 89.33  96.67 104.    85.  ]
Mean:  88.75
Maximum:  99.0
Minimum:  80.0
[[ 85  90  78]
 [ 92  88  95]
 [100  99  98]]
Average of each student:  [84.33333333 91.66666667 99.        ]
