In [7]:
#Numpy
import numpy as np

grades = np.array([84.33, 91.67, 99.0, 80.0])

print(grades)

#vectorization
bonus = grades + 5
print(bonus)

#Aggregation
print("Mean: ",grades.mean())
print("Maximum: ",grades.max())
print("Minimum: ", grades.min())

#2d array
students_grades = np.array([[85, 90, 78], [92, 88, 95], [100, 99, 98]])
print(students_grades)

print("Average of each student: ", students_grades.mean(axis = 1))

[84.33 91.67 99.   80.  ]
[ 89.33  96.67 104.    85.  ]
Mean:  88.75
Maximum:  99.0
Minimum:  80.0
[[ 85  90  78]
 [ 92  88  95]
 [100  99  98]]
Average of each student:  [84.33333333 91.66666667 99.        ]


In [8]:
"""
Build a small grade-processing script using ONLY NumPy operations — no 
Python loops allowed, to force real vectorization practice:

1. Create a 2D array: 4 students x 4 test scores (make up realistic numbers)
2. Calculate each student's average (axis-based, one line)
3. Calculate each TEST's average across all students (the other axis)
4. Find which student has the highest average (hint: look up np.argmax — 
   it returns the INDEX of the max value, not the value itself)
5. Add a 5-point curve to every score in the entire array (one line, 
   vectorized, no loop)
   """
import numpy as np
test_scores = np.array([[80, 90, 100, 70], [50, 60, 40, 70], [99, 70, 89, 70], [100, 99, 98, 89]])
print(test_scores)

average = test_scores.mean(axis = 1)
print("Average of each student: ", average)

average_column  = test_scores.mean(axis = 0)
print("Test's average across all students: ", average_column)

highest_average = np.argmax(average)
print("The highest average student is ", highest_average + 1, "th student")

added_test_scores = test_scores + 5
print(added_test_scores)




[[ 80  90 100  70]
 [ 50  60  40  70]
 [ 99  70  89  70]
 [100  99  98  89]]
Average of each student:  [85.  55.  82.  96.5]
Test's average across all students:  [82.25 79.75 81.75 74.75]
The highest average student is  4 th student
[[ 85  95 105  75]
 [ 55  65  45  75]
 [104  75  94  75]
 [105 104 103  94]]


In [21]:
"""
Guided Practice
1. Create a DataFrame from your students list (name, age, grades columns)
2. Use df.info() and df.describe() — look at the output, what does describe() 
   actually show you for the "grades" column, and why might that be weird/unhelpful?
3. Use boolean filtering: get only students older than 20
4. Add a new column "average" — compute each row's average grade (hint: 
   you'll need .apply() since grades is a list inside each cell — look this 
   up, it's new)
5. Use groupby: create an "age_group" column (e.g. "20s", "30s", "40s") 
   manually or with a simple function, then groupby that column and find 
   the mean average grade per group
   """
import pandas as pd

def age_group(age):
    if age > 0 and age <10:
        return "0s"
    elif age >= 10 and age <20:
        return "10s"
    elif age >=20 and age < 30:
        return "20s"
    elif age >= 30 and age < 40:
        return "30s"
    elif age >= 40 and age < 50:
        return "40s"
    else: 
        return None

students = [
    {"name": "Jack", "age": 19, "grades": [85, 90, 78]},
    {"name": "Priya", "age": 20, "grades": [92, 88, 95]},
    {"name": "John", "age": 24, "grades": [100, 99, 98]},
    {"name": "Alex", "age": 40, "grades": [70, 80, 90]}
]

df = pd.DataFrame(students)
print(df.info())
print(df.describe())

#boolean filtering
students_20 = df[df["age"] > 20]
print(students_20)

df["average"] = df["grades"].apply(lambda x: sum(x) / len(x))
print(df.head())

df["age_group"] = df["age"].apply(age_group)
print(df.head())

print(df.groupby("age_group")["average"].mean())

#Build challenge
"""
Using your students DataFrame (with average and age_group columns already added):

1. Find the student with the highest average grade (hint: you now know 
   two ways to do this — .idxmax() finds the INDEX of the max, similar 
   to NumPy's argmax; or sort and take the first row)

2. Group by age_group and show: mean average, count of students, using 
   .agg(["mean", "count"])

3. Create a new column "passed" — True if average >= 80, False otherwise 
   (hint: this can be done with a simple boolean comparison, similar to 
   how you'd filter, but assigned as a column instead)

4. Use boolean filtering to show only students who did NOT pass
"""
highest_grade_student = df["average"].idxmax()
print(f"The student number {highest_grade_student + 1} has the highest average grade")

print("Mean and no of students: ", df.groupby("age_group")["average"].agg(["mean", "count"]))

df["passed"] = df["average"].apply(lambda x: True if x >= 80 else False)
df.head()

print("List of failed student: ", df[df["passed"] != True])



<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      str   
 1   age     4 non-null      int64 
 2   grades  4 non-null      object
dtypes: int64(1), object(1), str(1)
memory usage: 228.0+ bytes
None
             age
count   4.000000
mean   25.750000
std     9.742518
min    19.000000
25%    19.750000
50%    22.000000
75%    28.000000
max    40.000000
   name  age         grades
2  John   24  [100, 99, 98]
3  Alex   40   [70, 80, 90]
    name  age         grades    average
0   Jack   19   [85, 90, 78]  84.333333
1  Priya   20   [92, 88, 95]  91.666667
2   John   24  [100, 99, 98]  99.000000
3   Alex   40   [70, 80, 90]  80.000000
    name  age         grades    average age_group
0   Jack   19   [85, 90, 78]  84.333333       10s
1  Priya   20   [92, 88, 95]  91.666667       20s
2   John   24  [100, 99, 98]  99.000000       20s
3   Alex   40   [70, 80, 9

In [12]:
#Debugging Challenge python
df = pd.DataFrame({
    "name": ["Jack", "Priya", "John"],
    "score": [85, 92, 78]
})

high_scorers = df["score"] > 80
print(high_scorers)

0     True
1     True
2    False
Name: score, dtype: bool
