In [7]:
#Numpy
import numpy as np

grades = np.array([84.33, 91.67, 99.0, 80.0])

print(grades)

#vectorization
bonus = grades + 5
print(bonus)

#Aggregation
print("Mean: ",grades.mean())
print("Maximum: ",grades.max())
print("Minimum: ", grades.min())

#2d array
students_grades = np.array([[85, 90, 78], [92, 88, 95], [100, 99, 98]])
print(students_grades)

print("Average of each student: ", students_grades.mean(axis = 1))

[84.33 91.67 99.   80.  ]
[ 89.33  96.67 104.    85.  ]
Mean:  88.75
Maximum:  99.0
Minimum:  80.0
[[ 85  90  78]
 [ 92  88  95]
 [100  99  98]]
Average of each student:  [84.33333333 91.66666667 99.        ]


In [8]:
"""
Build a small grade-processing script using ONLY NumPy operations — no 
Python loops allowed, to force real vectorization practice:

1. Create a 2D array: 4 students x 4 test scores (make up realistic numbers)
2. Calculate each student's average (axis-based, one line)
3. Calculate each TEST's average across all students (the other axis)
4. Find which student has the highest average (hint: look up np.argmax — 
   it returns the INDEX of the max value, not the value itself)
5. Add a 5-point curve to every score in the entire array (one line, 
   vectorized, no loop)
   """
import numpy as np
test_scores = np.array([[80, 90, 100, 70], [50, 60, 40, 70], [99, 70, 89, 70], [100, 99, 98, 89]])
print(test_scores)

average = test_scores.mean(axis = 1)
print("Average of each student: ", average)

average_column  = test_scores.mean(axis = 0)
print("Test's average across all students: ", average_column)

highest_average = np.argmax(average)
print("The highest average student is ", highest_average + 1, "th student")

added_test_scores = test_scores + 5
print(added_test_scores)




[[ 80  90 100  70]
 [ 50  60  40  70]
 [ 99  70  89  70]
 [100  99  98  89]]
Average of each student:  [85.  55.  82.  96.5]
Test's average across all students:  [82.25 79.75 81.75 74.75]
The highest average student is  4 th student
[[ 85  95 105  75]
 [ 55  65  45  75]
 [104  75  94  75]
 [105 104 103  94]]
