In [1]:
print("Hello world")
print("Revision phase 1")

Hello world
Revision phase 1


In [7]:
import numpy as np

X = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [20, 30, 40],
    [25, 35, 45],
    [30, 40, 50]
])

mean = X.mean(axis=0)
std = X.std(axis=0)

X_scaled = (X - mean) / std
print(mean, std, X_scaled, mean.shape, std.shape, X_scaled.shape)

[20. 30. 40.] [7.07106781 7.07106781 7.07106781] [[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]] (3,) (3,) (5, 3)


In [ ]:
#Two vectors